import type { Metadata } from "next";
import "./../style/globals.css";
import "./../style/resetcss.css";

export const metadata: Metadata = {
    title: "Yoldi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body>{children}</body>
        </html>
    );
}
